### ISSUE TITLE
Status Code not set, the client received a Status Code of 0, is this a problem?

### ISSUE THREAD

**Issue by vicbell** [Nike-Inc/cerberus-management-service#39]
In `GetCategory` line 65, the ResponseInfo not set HttpStatusCode, so the HttpStatusCode of the response is unknown, i think this should return a exact status code, do you think so?
```java
if (category.isPresent()) {
            return ResponseInfo.newBuilder(category.get()).build();
}
```

**Comment by nicmunroe** [comment]
@vicbell a 200 is used by default if no explicit status code is set on ResponseInfo. See [this javadoc on ResponseInfo](https://github.com/Nike-Inc/riposte/blob/master/riposte-spi/src/main/java/com/nike/riposte/server/http/ResponseInfo.java#L36).

**Comment by vicbell** [comment]
So sorry about my mistake, i test in a cors environment and status code display as 0 for some other reason.
